### ISSUE TITLE
Doesn't work with requires that have paths

### ISSUE THREAD

**Issue by stubailo** [bendrucker/replace-requires#1]
I'd like to use this to replace occurrences of `require('react/addons')` as in the example below:

``` js
var replaceRequires = require('replace-requires');

console.log(replaceRequires('require("react/addons")', {"react/addons": 'React'}));
//=> should return React, instead returns the original string
```

**Comment by bendrucker** [comment]
Good catch! This was an upstream regression caused by a perf feature I added to has-require. See the referenced commits.

**Comment by bendrucker** [comment]
Out as 1.0.3

**Comment by stubailo** [comment]
Awesome! I was going to track down where the problem was in has-require, but you got there first! Thanks.
