### ISSUE TITLE
consider accepting an array rather than object

### ISSUE THREAD

**Issue by iambumblehead** [bendrucker/replace-requires#2]
Thanks for sharing replace-requires. Please consider accepting an array param rather than an object. 

Here, the object parameter must be defined _before_ the call to replaceRequires

``` javascript
var replaceobj = {};
replaceobj[props[1].name] = key1;
replaceobj[props[2].name] = key2;

var finalcontent = replaceRequires(content, replaceobj);
```

Here, the parameter can be defined _in_ the call to replaceRequires (less ceremony)

``` javascript
var finalcontent = replaceRequires(content, [
  [props[1].name, key1],
  [props[2].name, key2]  
]);
```

Changes would be a few unobtrusive lines with current behaviour left as-is. If you would accept the change I'd be happy to make a PR.

**Comment by bendrucker** [comment]
Happy to review a PR if you can provide a better use case. In general I'm leaning no on this, especially since ES6 supports dynamic key names.

**Comment by iambumblehead** [comment]
``` javascript
replacerequires(umdstr, nodearr.reduce(function (prev, node) {
  return prev[node.refname] = node.name, prev;
}, {}));
```
