### ISSUE TITLE
I'm looking for a replace-imports, but no such thing exists --do you have any suggestions?

### ISSUE THREAD

**Issue by iambumblehead** [bendrucker/replace-requires#6]
I'm looking for a replace-imports, but no such thing exists --do you have any suggestions?

**Comment by bendrucker** [comment]
Not any modules in particular. This module uses `acorn` for AST parsing, you could certainly use it as a reference for how to use AST nodes and their `start`/`end` indexes to patch source code. I don't use `import` in any JS that I write/maintain so I can't justify the hour or so it might take to build it.
