### ISSUE TITLE
replace requires breaks with runtime error if es6 export/module are found in content

### ISSUE THREAD

**Issue by iambumblehead** [bendrucker/replace-requires#7]
for example this content
```javascript
let viewsall = {
  viewa : require('./viewa'),
  viewb : require('./viewb')
};

export default {
  start : () => {
    viewsall.viewa.start();
    viewsall.viewb.start();
  }
};
```
result in this error
```
SyntaxError: 'import' and 'export' may only appear at the top level (14:0)
```

**Comment by iambumblehead** [comment]
Upgrading to use the newest 'detective' resolves the issue
```
    "detective": "^5.1.0",
```
I would make a PR, but its just small change

**Comment by iambumblehead** [comment]
detective can be called in this way so that es6 mport export never cause runtime err
```javascript
detective(content, {
  parse: {
    sourceTy: 'module',
    allowImportExportEverywhe: true
  }
})
```

**Comment by bendrucker** [comment]
Hey please go ahead and send a PR! Don't just do the dependency change, add a test too. See https://github.com/bendrucker/replace-requires/commit/309c59475c27a88a25b04e174c3e840410de4922 which was the same thing but for a different syntax update.
